// Approved duration. Activation, paid entitlements and Stripe remain gated.
export const NEW_USER_TRIAL_DAYS=10;
export const NEW_USER_TRIAL_SECONDS=NEW_USER_TRIAL_DAYS*24*60*60;

// Consume a response generated by the authenticated server RPC. A browser date,
// localStorage flag or UI label must never be used to grant paid access.
export function trialSummary(state) {
  if(!state||state.days!==NEW_USER_TRIAL_DAYS||!['eligible','verify_email','unavailable','ineligible','active','expired'].includes(state.status))throw new Error('Unverified trial response.');
  if(!['active','expired'].includes(state.status))return {status:state.status,days:NEW_USER_TRIAL_DAYS};
  const start=Date.parse(state.started_at),end=Date.parse(state.ends_at),now=Date.parse(state.server_now);
  if(![start,end,now].every(Number.isFinite)||Math.abs(end-start-NEW_USER_TRIAL_SECONDS*1000)>1||now<start||
    !Number.isFinite(Number(state.remaining_seconds))||Number(state.remaining_seconds)<0||
    (state.status==='active')!==(now<end))throw new Error('Inconsistent trial response.');
  return {status:state.status,days:NEW_USER_TRIAL_DAYS,endsAt:state.ends_at,
    daysRemaining:state.status==='active'?Math.ceil(Math.max(0,end-now)/86400000):0,autoCharge:false};
}
