'use client';
import { useState } from 'react';
import dynamic from 'next/dynamic';
import { INTRO_DRILLS } from '@/lib/starterPolicy.mjs';
import './membership.css';
import ThemeToggle from './ThemeToggle';
import { hasOpenSubscription } from '@/lib/billingPolicy.mjs';
const WorkoutTimer = dynamic(() => import('@/components/train/WorkoutTimer'), { ssr: false,
  loading: () => <main className="membership-start"><p role="status">Getting your workout ready…</p><p>Your allowance is confirmed. Keep this screen open.</p></main>,
});

export default function FreeStarter({ state, busy = '', error = '', onClaim, onTrial, onRefresh, onHistory, onSignOut, sample = false }) {
  const [workout, setWorkout] = useState(false), [shots, setShots] = useState({ made: 0, attempts: 0 });
  const start = async () => { if (await onClaim()) setWorkout(true); };
  if (workout) return <WorkoutTimer drills={INTRO_DRILLS} persistResult={false} onClose={() => setWorkout(false)} onComplete={() => setWorkout(false)} />;
  const trial = state.billing?.trial;
  const subscriptionOpen = hasOpenSubscription(state.billing?.subscription);
  return <main className="membership-start" aria-label="CourtIQ free starter">
    <header className="starter-hero"><span className="starter-eyebrow">COURTIQ / FREE STARTER</span><h1>Your game.<br /><em>Your first step.</em></h1><p>Get a feel for the work. No countdown on free access.<br />{subscriptionOpen ? 'Manage your existing subscription below.' : 'No card for free access. An eligible trial starts only when you choose it.'}</p><div className="starter-actions" style={{alignItems:'center',marginTop:20}}><span className="starter-chip" style={{marginTop:0}}>FREE TO START · NOT A TRIAL</span><ThemeToggle /></div></header>
    {sample && <p role="note" className="starter-note">LOCAL SAMPLE · No database, account or payment changes.</p>}
    {error && <p role="alert" className="starter-error">{error}</p>}
    {subscriptionOpen && <p role="note" className="starter-error">Your existing subscription can still bill. Free access does not cancel it. <a href="/billing">Manage billing & cancellation</a> before changing plans. A new no-card trial is unavailable while that subscription remains open.</p>}
    <section className="starter-panel" aria-label="Free shot counter"><span className="starter-eyebrow">TRY THE FEEL</span><h2>Put a few shots up.</h2><p>A simple live counter, not a saved game. It resets when you leave or refresh.</p><div className="starter-score"><strong>{shots.made}<small>made</small></strong><span>/</span><strong>{shots.attempts}<small>attempts</small></strong></div><div className="starter-actions"><button className="starter-primary" onClick={() => setShots(s => ({ made: s.made + 1, attempts: s.attempts + 1 }))}>Made shot</button><button onClick={() => setShots(s => ({ ...s, attempts: s.attempts + 1 }))}>Missed shot</button><button aria-label="Reset unsaved shot counter" onClick={() => setShots({ made: 0, attempts: 0 })}>Reset</button></div></section>
    <section className="starter-panel" aria-label="Free training session"><span className="starter-eyebrow">01 / YOUR INTRO WORKOUT</span><h2>{state.workout === 'used' ? 'First reps, in the books.' : 'A little work. A real beginning.'}</h2><p>One introductory training session per account: form shooting, finishing and your free-throw routine. The result is not saved.</p><div className="starter-drills">{INTRO_DRILLS.map((drill, index) => <div key={drill.id}><span>0{index + 1}</span><strong>{drill.name}</strong><small>{drill.reps} reps</small></div>)}</div>{state.workout === 'available' ? <><button className="starter-primary starter-wide" disabled={!!busy} onClick={start}>{busy === 'workout' ? 'Checking your allowance…' : 'Start my one free workout'}</button><p className="starter-note">Your allowance is used when you start. Finishing, closing or refreshing won’t save a result or unlock another session. Keep this screen open.</p></> : <p className="starter-note">Your one free workout has been used. You can still use the unsaved shot counter.</p>}</section>
    <section className="starter-panel" aria-label="Free limits"><h2>What stays in premium.</h2><ul className="starter-limits"><li>Saved games and progress history</li><li>Further analytics and player comparisons</li><li>Additional training sessions and saved results</li><li>Journal entries and reflection history</li></ul><p>No fake locked charts. No hidden card requirement.</p></section>
    <section className="starter-upgrade" aria-label="Optional trial"><span className="starter-eyebrow">READY FOR MORE?</span><h2>Build a game<br />you can look back on.</h2><p>{subscriptionOpen ? 'An existing subscription must be managed separately. Starting free access does not stop renewals or outstanding payments.' : 'Choose a 10-day trial to try the fuller CourtIQ experience. No card. No automatic charge. One trial per eligible, verified account.'}</p>{trial?.status === 'eligible' && !subscriptionOpen ? <button className="starter-primary starter-wide" disabled={!!busy || !state.trialAvailable} onClick={onTrial}>{busy === 'trial' ? 'Starting your trial…' : 'Choose my 10-day trial'}</button> : <p className="starter-note">{subscriptionOpen ? 'Manage your existing subscription before changing plans.' : trial?.status === 'verify_email' ? 'Verify your signup email, then refresh to check trial eligibility.' : trial?.status === 'expired' ? 'Your trial has ended. Membership is a separate, explicit choice.' : 'Trial eligibility is checked on your account.'}</p>}<a className="starter-link" href="/billing">Review membership & trial status</a></section>
    <footer className="starter-actions"><button disabled={!!busy} onClick={onRefresh}>Refresh access</button>{onHistory && <button onClick={onHistory}>View previously saved records</button>}{onSignOut && <button onClick={onSignOut}>Sign out</button>}</footer>
    <p className="starter-note">This tier does not create or save a game, journal entry or workout result. A minimal account record tracks whether your free workout allowance has been used. Existing saved records are not deleted when access changes.</p>
  </main>;
}
