// Outline typography and export the native SVG artwork. This does not edit the
// image-generation raster concepts or ship a font file with the brand assets.
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';

const require = createRequire(new URL('../../package.json', import.meta.url));
const createFont = require('next/dist/compiled/@next/font/dist/fontkit').default;
const sharp = require('sharp');
const destination = new URL('../../public/brand/courtiq-v2/', import.meta.url);
await mkdir(destination, { recursive: true });
const fontPath = process.argv[2] || '/System/Library/Fonts/Supplemental/Arial Black.ttf';
const font = createFont(await readFile(fontPath));
const run = font.layout('CourtIQ');
const markSource = await readFile(new URL('./mark-source.svg', import.meta.url), 'utf8');
const mark = markSource.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').replace(/<title[\s\S]*?<\/title>/, '');
const scale = 124 / font.unitsPerEm;
const baseline = 98;
let advance = 0;
const shapes = run.glyphs.map((glyph, index) => {
  const position = run.positions[index];
  const x = 151 + (advance + position.xOffset) * scale - index * 1.15;
  const y = baseline - position.yOffset * scale;
  advance += position.xAdvance;
  return { index, path: `<g transform="translate(${x.toFixed(3)} ${y.toFixed(3)}) scale(${scale.toFixed(7)} -${scale.toFixed(7)})"><path d="${glyph.path.toSVG()}"/></g>` };
});
const width = Math.ceil(151 + advance * scale - 6 * 1.15 + 5);
const header = (title, w, h) => `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}" role="img" aria-labelledby="courtiq-title"><title id="courtiq-title">${title}</title>`;
for (const [name, courtColor, accent] of [['light', '#161B24', '#FF6B35'], ['dark', '#FFFFFF', '#FF6B35'], ['mono', '#161B24', '#161B24']]) {
  const coloredMark = mark.replaceAll('#FF6B35', accent);
  const text = shapes.map(({ index, path }) => `<g fill="${index < 5 ? courtColor : accent}">${path}</g>`).join('');
  const svg = `${header('CourtIQ', width, 120)}${coloredMark}${text}</svg>`;
  await writeFile(new URL(`courtiq-logo-${name}.svg`, destination), svg);
  await sharp(Buffer.from(svg)).resize({ width: 2400 }).png().toFile(fileURLToPath(new URL(`courtiq-logo-${name}.png`, destination)));
}
await writeFile(new URL('courtiq-mark.svg', destination), markSource);
await sharp(Buffer.from(markSource)).resize({ width: 1024 }).png().toFile(fileURLToPath(new URL('courtiq-mark.png', destination)));
const icon = `${header('CourtIQ home-screen icon', 512, 512)}<rect width="512" height="512" rx="112" fill="#161B24"/><g transform="translate(64 69) scale(3)">${mark}</g></svg>`;
await writeFile(new URL('courtiq-app-icon.svg', destination), icon);
await sharp(Buffer.from(icon)).resize(512, 512).png().toFile(fileURLToPath(new URL('courtiq-app-icon.png', destination)));
for (const size of [48, 192, 512]) {
  await sharp(Buffer.from(icon)).resize(size, size).png().toFile(fileURLToPath(new URL(`icon-${size}.png`, destination)));
}
// Full-bleed background and a smaller mark keep every visible pixel inside
// the central 80% safe circle for Android's maskable launcher icon.
const maskable = `${header('CourtIQ maskable icon', 512, 512)}<rect width="512" height="512" fill="#161B24"/><g transform="translate(102 108) scale(2.4)">${mark}</g></svg>`;
await writeFile(new URL('courtiq-maskable.svg', destination), maskable);
await sharp(Buffer.from(maskable)).png().toFile(fileURLToPath(new URL('icon-maskable-512.png', destination)));
const apple = icon.replace(' rx="112"', '');
await sharp(Buffer.from(apple)).resize(180, 180).png().toFile(fileURLToPath(new URL('apple-touch-icon.png', destination)));
const darkSvg = await readFile(new URL('courtiq-logo-dark.svg', destination), 'utf8');
const darkPaths = darkSvg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').replace(/<title[\s\S]*?<\/title>/, '');
// Self-contained artwork lets social exports render without fetching an image
// from a Blob-backed SVG (which browsers may block or use to taint a canvas).
await writeFile(new URL('../../src/lib/brandArtwork.mjs', import.meta.url), `// Generated by design/courtiq-brand-v2/build-logo.mjs. No external assets.\nexport const COURTIQ_DARK_LOGO_PATHS = ${JSON.stringify(darkPaths)};\n`);
console.log(JSON.stringify({ destination: fileURLToPath(destination), format: 'font-independent SVG paths and transparent PNG exports', wordmark: 'CourtIQ', width, height: 120, fontFoundation: font.familyName }));
