import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import { PGlite } from '@electric-sql/pglite';
const alice='00000000-0000-0000-0000-000000000001',bob='00000000-0000-0000-0000-000000000002',old='00000000-0000-0000-0000-000000000003',unverified='00000000-0000-0000-0000-000000000004';
const player='10000000-0000-0000-0000-000000000001';
const migrations=['20260930171602_web_player_ownership_safeguards.sql','20260930202201_reliable_sessions_and_development.sql','20261001144325_owned_roster_games.sql','20261001151920_ten_day_new_user_trials.sql','20261001170545_courtiq_subscription_core.sql','20261001175225_premium_player_analytics.sql','20261001184745_trial_checkout_exclusion.sql'];
test('starter is once per owner; new game, journal and saved-workout writes denied, legacy history and trial access survive',async()=>{
  const db=new PGlite();
  try{
    await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;
      create table auth.users(id uuid primary key,created_at timestamptz default clock_timestamp(),email_confirmed_at timestamptz);
      create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
      grant usage on schema auth to authenticated,service_role;
      insert into auth.users(id,email_confirmed_at) values('${alice}',clock_timestamp()),('${bob}',clock_timestamp());
      insert into auth.users(id,created_at,email_confirmed_at) values('${old}','2020-01-01',clock_timestamp());
      insert into auth.users(id) values('${unverified}');`);
    await db.exec(await readFile(new URL('../supabase/schema.sql',import.meta.url),'utf8'));
    await db.exec(`insert into players(id,firebase_uid,manager_uid,name) values('${player}','${alice}','${alice}','Fixture');`);
    for(const file of migrations)await db.exec(await readFile(new URL(`../supabase/migrations/${file}`,import.meta.url),'utf8'));
    const user=uid=>db.exec(`reset role;set request.jwt.claim.sub='${uid}';set role authenticated;`);
    const state=async()=>(await db.query('select get_courtiq_starter() value')).rows[0].value;
    await user(alice);assert.equal((await state()).mode,'legacy');
    const saved=(await db.query(`insert into sessions(player_id,type) values('${player}','game') returning id`)).rows[0].id;
    await db.exec('reset role;');await assert.rejects(db.exec('update private.courtiq_starter_policy set enabled=true'),/grandfather cutoff/);
    await db.exec("update private.courtiq_billing_policy set enforce_access=true,grandfather_before='2021-01-01';update private.courtiq_starter_policy set enabled=true;update private.courtiq_trial_policy set enabled=true,new_user_since='2021-01-01';");
    await assert.rejects(db.exec('update private.courtiq_billing_policy set grandfather_before=null'),/grandfather cutoff/);
    await user(alice);assert.equal((await state()).mode,'free');assert.equal((await state()).workout,'available');
    const request=randomUUID();
    const claim=async id=>(await db.query('select claim_courtiq_starter($1) value',[id])).rows[0].value;
    assert.equal((await claim(request)).granted,true);assert.equal((await claim(request)).request_id,request);
    await assert.rejects(claim(randomUUID()),/already used/);assert.equal((await state()).workout,'used');
    assert.equal((await db.query('select id from sessions')).rows[0].id,saved);
    await assert.rejects(db.query(`insert into sessions(player_id,type) values('${player}','game')`),/PLAN_REQUIRED/);
    await assert.rejects(db.query(`insert into journal_entries(player_id,type,mood,title) values('${player}','game','good','Fixture')`),/PLAN_REQUIRED/);
    await assert.rejects(db.query(`insert into workout_results(id,player_id,elapsed_seconds,drills) values($1,'${player}',1,'[]')`,[randomUUID()]),/PLAN_REQUIRED/);
    await assert.rejects(db.query('select * from private.courtiq_starter_usage'),/permission denied/);
    await user(bob);assert.equal((await state()).workout,'available');await claim(randomUUID());
    assert.equal((await db.query(`update sessions set coverage_confirmed=true where id='${saved}' returning id`)).rows.length,0);
    await user(unverified);await assert.rejects(claim(randomUUID()),/Verify your email/);
    await user(old);assert.equal((await state()).mode,'full');assert.equal((await state()).billing.access,'legacy');
    await user(alice);await db.query('select start_courtiq_trial()');assert.equal((await state()).mode,'full');
    await db.query(`insert into sessions(player_id,type) values('${player}','game')`);
    await db.query(`insert into journal_entries(player_id,type,mood,title) values('${player}','game','good','Fixture')`);
    await db.query(`insert into workout_results(id,player_id,elapsed_seconds,drills) values($1,'${player}',1,'[{"name":"Fixture"}]')`,[randomUUID()]);
    await db.exec(`reset role;update account_trials set started_at=started_at-interval '11 days',ends_at=ends_at-interval '11 days';`);
    await user(alice);assert.equal((await state()).mode,'free');assert.equal((await state()).workout,'used');assert.equal((await db.query('select count(*)::int n from sessions')).rows[0].n,2);
    await db.exec('reset role;set role anon;');await assert.rejects(db.query('select get_courtiq_starter()'),/permission denied/);
  }finally{await db.close();}
});
