'use client';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import Link from 'next/link';
import { COURT_ZONES } from '@/lib/constants';
import { premiumAnalysis, STYLE_FEATURES } from '@/lib/premiumAnalytics.mjs';
import { NBA_REFERENCE_SOURCES } from '@/lib/nbaReferences.mjs';
import './premium.css';
const number = value => value === null || value === undefined ? '—' : value.toFixed(1);
const pct = value => value === null || value === undefined ? '—' : `${value.toFixed(1)}%`;
async function analyticsApi(body, signal) {
  const response = await fetch('/api/analytics', { method: body ? 'PATCH' : 'GET', credentials: 'same-origin', cache: 'no-store', signal,
    ...(body ? { headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) } : {}) });
  const result = await response.json();
  if (!response.ok) throw new Error(result.error || 'Analytics could not load. Please retry.');
  return result;
}
export function PremiumView({ dataset, onCoverage, busy = '', sample = false }) {
  const [selected, setSelected] = useState(dataset.players[0]?.id || ''), [compare, setCompare] = useState('');
  const player = dataset.players.find(player => player.id === selected);
  const sessions = useMemo(() => dataset.sessions.filter(session => session.player_id === selected), [dataset.sessions, selected]);
  const analysis = useMemo(() => premiumAnalysis(sessions, COURT_ZONES), [sessions]);
  const comparison = useMemo(() => compare ? premiumAnalysis(dataset.sessions.filter(session => session.player_id === compare), COURT_ZONES) : null, [compare, dataset.sessions]);
  const { aggregate, nba, recent, prior } = analysis;
  const per36 = [['pts','PTS'],['ast','AST'],['reb','REB'],['stl','STL'],['blk','BLK'],['to','TO']];
  return <div className="premium-lab">
    <header className="premium-hero"><span className="premium-eyebrow">COURTIQ / PERFORMANCE LAB</span><h2>Know your game.<br /><em>Build your edge.</em></h2><p>More context. Better questions. A clearer next session.</p><span className="premium-chip">{sample ? 'LOCAL SYNTHETIC SAMPLE' : 'PRIVATE · YOUR ACCOUNT'}</span></header>
    <label className="premium-select">Analyze player<select value={selected} onChange={event => { setSelected(event.target.value); setCompare(''); }}>{dataset.players.map(profile => <option value={profile.id} key={profile.id}>{profile.name} · {profile.position}</option>)}</select></label>
    <section className="premium-panel"><div className="premium-section-heading"><h3>{player?.name || 'Your'} game, in context.</h3><span>{aggregate.games} confirmed games</span></div><p>{aggregate.fga} field-goal attempts · {aggregate.min} minutes. {analysis.recordedGames - aggregate.games} logged game(s) excluded from full-box-score analysis.</p><div className="premium-metrics">{[['eFG%',pct(aggregate.efgPct),'Accounts for 3-point value'],['Estimated TS%',pct(aggregate.tsPct),'FT estimate; not exact possessions'],['AST / TO',number(aggregate.astTo),aggregate.to ? `${aggregate.ast} assists / ${aggregate.to} turnovers` : 'Undefined with zero turnovers'],['3PT%',pct(aggregate.threePct),`${aggregate.threeMade} / ${aggregate.threeAttempts} attempts`]].map(([label,value,note]) => <div key={label}><span>{label}</span><strong>{value}</strong><small>{note}</small></div>)}</div><details><summary>How the sample is chosen</summary><p>Only completed games with owner-confirmed full shot and box-score coverage, valid counts, dates and minutes. Confirmation is self-reported, not an independent audit. Practice is excluded. Percentages are calculated from total makes and attempts, not averaged game percentages.</p></details></section>
    <section className="premium-panel"><span className="premium-eyebrow">YOUR STATISTICAL DNA</span><h3>NBA style echoes.</h3><p>Historical statistical-pattern comparisons—not talent ratings, scouting, future NBA potential or an endorsement.</p>{nba.available ? <>{nba.weakMatch && <p role="note" className="premium-caution">Your pattern is not particularly close to this reference set. These are relative nearest neighbors, not strong matches.</p>}<div className="premium-matches">{nba.matches.map((match,index) => <article key={match.name}><span className="premium-match-rank">0{index+1}</span><div><h4>{match.name}</h4><p>Pattern distance {match.distance.toFixed(2)} · lower is closer, not a confidence score</p><div className="premium-feature-tags">{match.closestFeatures.map(feature => <span key={feature.key}>{feature.label}</span>)}</div><p className="premium-fine">Biggest difference: {match.largestDifference.label}. Yours {(match.largestDifference.yours*100).toFixed(1)}%; reference {(match.largestDifference.reference*100).toFixed(1)}%.</p></div></article>)}</div>{analysis.styleTrend && <p className="premium-trend">Last 5 versus previous 5 confirmed games: your pattern is {analysis.styleTrend.direction === 'closer' ? 'moving closer to' : analysis.styleTrend.direction === 'further' ? 'moving further from' : 'roughly steady relative to'} the {analysis.styleTrend.name} reference. Descriptive change, not a prediction.</p>}</> : <div className="premium-empty"><strong>Your style needs a sample, not a guess.</strong><p>Record at least 5 full games, 100 total minutes and 50 field-goal attempts, with assists, rebounds, steals and blocks logged. Current: {aggregate.games} games · {aggregate.min} minutes · {aggregate.fga} attempts.</p></div>}<details><summary>Reference season & matching method</summary><p>Eight curated references, {nba.season}. Not the entire NBA or a live ranking. Six equal-weight relative features: {STYLE_FEATURES.map(feature => feature.label).join(', ')}. Contribution shares divide AST, REB, STL or BLK by their combined total—not team possessions. Mean absolute feature difference is scaled by fixed design choices (.20, .20, .15, .15, .10, .10). The sample threshold and distance labels are product guardrails, not statistically validated confidence estimates.</p><p>Reference figures use rounded published per-game values. <a href={NBA_REFERENCE_SOURCES[0]} target="_blank" rel="noopener noreferrer">NBA season leaders</a> · <a href={NBA_REFERENCE_SOURCES[1]} target="_blank" rel="noopener noreferrer">Assist leaders</a>. Independent CourtIQ feature; no NBA affiliation.</p></details></section>
    <section className="premium-panel"><span className="premium-eyebrow">THE WORK, OVER TIME</span><h3>Momentum you can inspect.</h3>{analysis.trendAvailable ? <div className="premium-trend-grid">{[['eFG%',prior.efgPct,recent.efgPct,true],['Estimated TS%',prior.tsPct,recent.tsPct,true],['PTS / 36',prior.per36.pts,recent.per36.pts,false],['AST / 36',prior.per36.ast,recent.per36.ast,false]].map(([label,before,after,isPct]) => <div key={label}><span>{label}</span><strong>{isPct ? pct(before) : number(before)} → {isPct ? pct(after) : number(after)}</strong><small>{before === null || after === null ? 'Not enough attempts' : `${after-before>=0?'+':''}${(after-before).toFixed(1)} ${isPct?'percentage points':'per 36'}`}</small></div>)}</div> : <div className="premium-empty"><p>Ten confirmed games unlock two non-overlapping five-game windows. No progress claim is made from one game.</p></div>}<p className="premium-fine">Per-36 values normalize logged minutes. They are not expected production, opponent-adjusted impact or a player ranking.</p></section>
    <section className="premium-panel"><span className="premium-eyebrow">OWN YOUR SPOTS</span><h3>Where the attempts went.</h3>{aggregate.zones.length ? <div className="premium-zones">{aggregate.zones.map(zone => <div key={zone.id}><div><strong>{zone.label}</strong><span>{zone.made}/{zone.attempts} · {pct(zone.pct)}</span></div><progress value={zone.made} max={zone.attempts} aria-label={`${zone.label}: ${zone.made} made of ${zone.attempts}`} /></div>)}</div> : <p>Confirm a full game's coverage to populate your shot zones.</p>}</section>
    <section className="premium-panel"><span className="premium-eyebrow">SIDE BY SIDE</span><h3>Compare players you manage.</h3><p>Private roster comparison—not other customers' identities or records. Different competition, roles and logging quality affect these numbers.</p><label className="premium-select">Compare with<select value={compare} onChange={event => setCompare(event.target.value)}><option value="">Choose a saved player</option>{dataset.players.filter(profile => profile.id !== selected).map(profile => <option value={profile.id} key={profile.id}>{profile.name}</option>)}</select></label>{comparison && <><p>{aggregate.games} vs {comparison.aggregate.games} confirmed games · {aggregate.min} vs {comparison.aggregate.min} minutes</p><div className="premium-comparison"><table><caption>Recorded totals normalized per 36 minutes; not a skill ranking</caption><thead><tr><th scope="col">Per 36</th><th scope="col">{player?.name}</th><th scope="col">{dataset.players.find(profile=>profile.id===compare)?.name}</th></tr></thead><tbody>{per36.map(([key,label])=><tr key={key}><th scope="row">{label}</th><td>{number(aggregate.per36[key])}</td><td>{number(comparison.aggregate.per36[key])}</td></tr>)}</tbody></table></div></>}{dataset.players.length < 2 && <p className="premium-fine">A second owner-managed player with recorded games is needed. Shared coach/player invitations are not implied by this view.</p>}</section>
    <section className="premium-panel"><h3>CourtIQ community benchmarks</h3><p>Not activated. Your stats are not being shared with other accounts. Anonymous, opt-in, adequately sized cohorts and youth/guardian safeguards need review before cross-account comparisons are released. No fabricated percentiles or small-group leaderboards.</p></section>
    <details className="premium-panel"><summary>Review game coverage</summary><p>Only confirm a game if you recorded the entire shot ledger and full box score, including minutes and zeros. Do not check this just to unlock a match.</p>{sessions.map(session => <div key={session.id} className="premium-coverage-row"><span>{session.date}<small>{analysis.excluded.find(item=>item.id===session.id)?.reason || 'Included · owner-confirmed coverage'}</small></span><button disabled={!!busy} onClick={() => onCoverage(session.id,!session.coverage_confirmed)}>{session.coverage_confirmed ? 'Undo confirmation' : 'Confirm full game'}</button></div>)}{!sessions.length && <p>No completed games to review.</p>}</details>
    <p className="premium-fine">Team ratings, usage, plus/minus and exact possession efficiency need data CourtIQ does not currently record and are not invented here. <a href="https://www.nba.com/stats/help/glossary" target="_blank" rel="noopener noreferrer">Metric definitions</a>.</p>
  </div>;
}
export default function PremiumAnalytics({ api = analyticsApi }) {
  const [data,setData] = useState(null),[error,setError] = useState(''),[busy,setBusy] = useState('');
  const mounted=useRef(false), inFlight=useRef(false);
  const load=useCallback(async signal=>{const next=await api(null,signal);if(!signal?.aborted&&mounted.current){setData(next);setError('');}},[api]);
  useEffect(()=>{mounted.current=true;const controller=new AbortController();load(controller.signal).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>{mounted.current=false;controller.abort();};},[load]);
  const coverage=async(sessionId,confirmed)=>{if(inFlight.current)return;inFlight.current=true;setBusy(sessionId);try{await api({sessionId,confirmed});await load();}catch(e){if(mounted.current)setError(e.message);}finally{inFlight.current=false;if(mounted.current)setBusy('');}};
  if(!data)return <section className="premium-panel"><h2>Performance Lab</h2><p role="status">{error||'Verifying your membership and game records…'}</p>{error&&<><button onClick={()=>load().catch(e=>setError(e.message))}>Retry</button><Link href="/billing">Review membership</Link></>}</section>;
  return <>{error&&<p role="alert">{error}</p>}<PremiumView dataset={data} onCoverage={coverage} busy={busy}/></>;
}
